version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=security
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
volumes:
  volume: